var basicBool = "checkbox";
var simpleDogStates = [
    "Initial state",
    "Killed",
    "Played fetch (Spared)"
];

var items = [
    "Empty",
    "Monster Candy",
    "Croquet Roll",
    "Stick",
    "Bandage",
    "Rock Candy",
    "Pumpkin Rings",
    "Spider Donut",
    "Stoic Onion",
    "Ghost Fruit",
    "Spider Cider",
    "Butterscotch Pie",
    "Faded Ribbon",
    "Toy Knife",
    "Tough Glove",
    "Manly Bandana",
    "Snowman Piece",
    "Nice Cream",
    "Puppydough Icecream",
    "Bisicle",
    "Unisicle",
    "Cinnamon Bun",
    "Temmie Flakes",
    "Abandoned Quiche",
    "Old Tutu",
    "Ballet Shoes",
    "Punch Card",
    "Annoying Dog",
    "Dog Salad",
    "Dog Residue (1)",
    "Dog Residue (2)",
    "Dog Residue (3)",
    "Dog Residue (4)",
    "Dog Residue (5)",
    "Dog Residue (6)",
    "Astronaut Food",
    "Instant Noodles",
    "Crab Apple",
    "Hot Dog...?",
    "Hot Cat",
    "Glamburger",
    "Sea Tea",
    "Starfait",
    "Legendary Hero",
    "Cloudy Glasses",
    "Torn Notebook",
    "Stained Apron",
    "Burnt Pan",
    "Cowboy hat",
    "Empty Gun",
    "Heart Locket",
    "Worn Dagger",
    "Real Knife",
    "The Locket",
    "Bad Memory",
    "Dream",
    "Undyne's Letter",
    "Undyne Letter EX",
    "Potato Chisps",
    "Junk Food",
    "Mystery Key",
    "Face Steak",
    "Hush Puppy",
    "Snail Pie",
    "temy armor",
    "<invalid>"
];

var flags = [
    // Format of [name (String), description (String), options (Object)]
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["undyne_trigger_override", "Debug variable. Allows Undyne to give her Pacifist speech even if one (but only one) monster is killed.", basicBool],
    ["fun", "The fun value. See above list for effects."],
    ["hardmode", "Hard Mode.", basicBool],
    ["true_pacifist", "In the Pacifist epilogue.", basicBool],
    ["disable_random_encounters", "Self-explanatory. Set at the start of the Undyne's Letter quest or after defeating Mettaton NEO.", basicBool],
    ["flowey_seen_stalking", "Unaccessed. Tracks how often you backtracked to catch Flowey."],
    ["spared_last", "Whether you spared the previous enemy.", basicBool],
    ["escaped_last", "Whether you fled the previous battle.", basicBool],
    ["killed_last", "Whether you killed the previous enemy.", basicBool],
    ["bored_last", "Intended for Dummy. Copied to all Ruins enemies.", basicBool],
    ["status_dummy", "What you did to that poor, poor Dummy.", [
        "Escaped from",
        "Killed",
        "Talked to",
        "Bored"
    ]],
    ["in_battle", "Whether you are in a battle.", basicBool],
    ["type_heart_transition", "Whether you are entering a 'quick' battle.", basicBool],
    ["menu_disabled", "Whether you cannot access your menu due to an overworld event (e.g. Undyne chasing you).", basicBool],
    ["view_rotated", "Whether the view is rotated. Only used for Undyne's speech.", basicBool],
    ["unused"],
    ["animation_index", "Certain enemies' current animation frame."],
    ["cooked_noodles", "Whether you are cooking the Instant Noodles. Makes the text unskippable in battle.", basicBool],
    ["name_color", "Color of the names of spareable enemies.", [
        "Yellow",
        "White",
        "Pink"
    ]],
    ["spared", "How many enemies you have spared."],
    ["escaped", "How many enemies you have fled from."],
    ["dialogues_skipped", "How many textboxes you have skipped."],
    ["murderlevel_override", "Debug variable. Overrides the Genocide Route progress. Normally, each level also requires all previous levels to be met.", {
        "0": "No murder level",
        "1": "20 Ruins kills",
        "2": "Toriel",
        "3": "Doggo",
        "4": "Dogi",
        "5": "Greater Dog",
        "6": "Snowdrake",
        "7": "16 Snowdin kills",
        "8": "Papyrus",
        "9": "Shyren",
        "10": "Glad Dummy",
        "11": "18 Waterfall kills",
        "12": "Undyne",
        "13": "Royal Guards",
        "14": "Muffet",
        "15": "40 Hotland kills",
        "16": "Mettaton",
        "50": "Level 50 (Debug)"
    }],
    ["spared_specific", "Whether you spared certain bosses or minibosses, aborting the Genocide Route.", basicBool],
    ["fast_text_skip", "Debug variable. Makes [C] skip most text at 7.5 textboxes per second.", basicBool],
    ["unused"],
    ["tutorial_froggit_met", "Whether you have fought the scripted Froggit.", basicBool],
    ["pushed_rock_1", "Whether you have pushed the middle rock.", basicBool],
    ["pushed_rock_2", "Whether you have pushed the top rock.", basicBool],
    ["pushed_rock_3", "Whether you have completed the second rock-pushing puzzle.", basicBool],
    ["candy_taken", "How much Monster Candy you have taken.", [
        "None",
        "One piece",
        "Two pieces",
        "Three pieces",
        "Four pieces, you Monster."
    ]],
    ["pushed_rock_4", "Whether you have completed the first rock-pushing puzzle.", basicBool],
    ["spared_napstablook", "Tracks your interaction with Napstablook in the Ruins.", [
        "Inital state",
        "Spared",
        "Spared, met in hole"
    ]],
    ["dog_call_status", "Tracks the Toriel phone calls when waiting, especially about the Annoying Dog.", [
        "Initial state",
        "Dog has Toriel's phone",
        "Toriel's phone recovered"
    ]],
    ["unused"],
    ["unused"],
    ["greeted_toriel", "How many times you have called Toriel to say hello."],
    ["flirted_toriel", "How many times you have called Toriel to flirt with her."],
    ["call_mom_toriel", "Whether you have called Toriel 'mom'.", basicBool],
    ["ruins_switches_pressed", "When greater than 25, changes the displayed text upon pressing a switch."],
    ["disobeyed_toriel", "How many times Toriel had to return you upstairs."],
    ["status_toriel", "Self-explanatory.", {
        "0": "Initial state",
        "1": "In basement",
        "3": "Fled from",
        "4": "Killed",
        "5": "Spared"
    }],
    ["choice_flavor", "Your choice for Toriel's pie flavor.", [
        "Cinnamon",
        "Butterscotch"
    ]],
    ["status_creepy_tundra", "Partly handles progress through the 'creepy' part of Sans's introduction scene.", {
        "0": "Initial state",
        "2": "Stick broken",
        "3": "Sans spotted",
        "-1": "Scene complete",
    }],
    ["unused"],
    ["unused"],
    ["know_water_sausage", "Read about water sausages in Toriel's room. Makes you recognize the plant in Toriel's living room.", basicBool],
    ["wrong_switches_pressed", "Gives you a hint after two failures."],
    ["status_doggo", "Self-explanatory.", simpleDogStates],
    ["status_dogcouple", "Self-explanatory.", simpleDogStates],
    ["status_greaterdog", "Self-explanatory.", [
        "Inital state",
        "Killed",
        "Played fetch (Spared)",
        "Ignored"
    ]],
    ["status_lesserdog", "Self-explanatory.", [
        "Initial state",
        "Killed",
        "Continued petting [Yellow credit]"
    ]],
    ["status_snowman", "Status of the snowman in Snowdin Forest (Neutral/Pacifist).", {
        "0": "Initial state",
        "1": "Have a Snowman Piece",
        "2": "Have a second Snowman Piece",
        "4": "Ate the Piece in front of him",
        "5": "Talked to him after"
    }],
    ["status_snowdrake", "Self-explanatory.", [
        "Initial state",
        "Laughed at joke [Yellow credit]",
        "Killed"
    ]],
    ["choice_harder_puzzle", "Which puzzle you told Sans and Papyrus was harder.", [
        "Junior Jumble",
        "Crossword"
    ]],
    ["spider_donations_total", "How much money you've given to either Spider Bake Sale."],
    ["nicecream_donations_total", "How much money you've spent on Nice Cream (+1 for talking to him at all)."],
    ["unused"],
    ["choice_ate_left_spaghetti", "What you told Papyrus you did with his spaghetti. Affects phone dialogue in the spaghetti room.", [
        "Initial state",
        "Ate it",
        "Left it"
    ]],
    ["xoxo_resets", "How many times you failed the second XO puzzle. Affects Sans's dialogue in the room."],
    ["toggled_snow_switch", "Status of the hidden switch puzzle in the Dogi/Lesser Dog room.", {
        "-1": "Moved the snow",
        "0": "Initial state",
        "1": "Pressed switch w/o moving snow or on Genocide"
    }],
    ["got_snowpoff_gold", "Self-explanatory.", basicBool],
    ["flirted_papyrus_fight", "Self-explanatory. Changes his hangout to a date.", basicBool],
    ["status_papyrus", "Self-explanatory.", {
        "-3": "Lost to thrice",
        "-2": "Lost to twice",
        "-1": "Lost to once",
        "0": "Initial state",
        "1": "Killed"
    }],
    ["fought_papyrus", "Self-explanatory. Basically used for the cutscene to tell if the fight is done. Reset each refight.", basicBool],
    ["bpants_alt_dialogue", "Debug variable. Slightly alters Burgerpants's dialogue in old versions of the game; appears intended to track being in shops before. Unused in newer versions.", basicBool],
    ["progress_tundra_battles", "Loosely, how many Snowdin encounters you've had. Guarantees you encounter a variety of enemies.", {
        "0": "Initial state",
        "1": "Encountered Snowdrake",
        "2": "Encountered Ice Cap",
        "4": "Encountered Lesser Dog"
    }],
    ["unused"],
    ["status_inn", "Tracks your interaction with the innkeep.", [
        "Initial state",
        "Stayed a night",
        "Stayed a night with no money"
    ]],
    ["in_inn", "Whether you are currently sleeping in the inn.", basicBool],
    ["betrayed_gyftrot", "Whether you cruelly added another decoration to Gyftrot. Unaccessed.", basicBool],
    ["armor_papyrus_inquiry", "The armor you were wearing when Papyrus called to ask.", {
        "0": "Initial state",
        "4": "Bandage",
        "12": "Faded Ribbon",
        "15": "Manly Bandana",
        "24": "Old Tutu",
        "44": "Cloudy Glasses (impossible)",
        "46": "Stained Apron (impossible)",
        "48": "Cowboy Hat (impossible)",
        "50": "Heart Locket (impossible)",
        "53": "The Locket (impossible)",
        "64": "temy armor (impossible)"
    }],
    ["choice_papyrus_inquiry", "What you told Papyrus about your armor", [
        "Truth",
        "Lied"
    ]],
    ["armor_undyne_saw", "The armor Undyne saw you wearing. Affect's Papyrus's call about it.", {
        "0": "Initial state",
        "4": "Bandage",
        "12": "Faded Ribbon",
        "15": "Manly Bandana",
        "24": "Old Tutu",
        "44": "Cloudy Glasses (impossible)",
        "46": "Stained Apron (impossible)",
        "48": "Cowboy Hat (impossible)",
        "50": "Heart Locket (impossible)",
        "53": "The Locket (impossible)",
        "64": "temy armor (impossible)"
    }],
    ["strong_tough_glove", "Whether you tore up a Punch Card in the current battle, strengthening the Tough Glove.", basicBool],
    ["nicecream_business", "Whether you interacted with Nice Cream Guy in Waterfall.", {
        "0": "Initial state",
        "8": "Interacted"
    }],
    ["punchcards_bought", "The amount of Punch Cards in the Punch Card Box."],
    ["status_shyren", "Self-explanatory.", [
        "Initial state",
        "Killed",
        "Continued humming [Yellow credit]"
    ]],
    ["papyrus_sink_event_occurred", "Self-explanatory.", basicBool],
    ["got_couch_gold", "Self-explanatory.", basicBool],
    ["mushroom_talk_progress", "Your status with the inaccessible NPC in room_water_mushroom.", {
        "0": "Initial state",
        "2": "Accepted request",
        "3": "Returned (impossible)",
        "4": "Said it was different",
        "5": "Said it was the same"
    }],
    ["have_umbrella", "Self-explanatory.", basicBool],
    ["music_statue_on", "Whether you've given the music statue an umbrella.", basicBool],
    ["unused"],
    ["dated_papyrus", "Tracks progress through Papyrus's date.", [
        "Initial state",
        "Spared Papyrus",
        "Papyrus in house",
        "Unlocked Papyrus's room",
        "Date/hangout complete"
    ]],
    ["dated_sans1", "Tracks progress through the Grillby's hangout", [
        "Initial state",
        "In Grillby's",
        "Hangout complete"
    ]],
    ["choice_mkid_umbrella", "Tracks Monster Kid's knowledge of your umbrella habits.", [
        "Initial state",
        "Met without umbrella",
        "Met with umbrella",
        "Put umbrella back"
    ]],
    ["trash_save_mkid_pos", "Tracks progress through the Monster Kid following sequence... and interacting with the Garbage Dump save point.", {
        "0": "Initial state",
        "1": "'Undyne is sooooooo cool.'/Interacted with save",
        "3": "'How COOL would it be if UNDYNE came to school!?'",
        "4": "'She's too cool to ever hurt an innocent person!'",
        "6": "Seen castle",
        "10": "Scene complete"
    }],
    ["status_stable", "Tracks the status of the unused stable and its key.", [
        "Initial state",
        "[redacted] in stable (impossible)",
        "Interacted with [redacted]",
        "Key acquired",
        "Stable unlocked (impossible)"
    ]],
    ["dated_napstablook", "Tracks progress through Napstablook's house.", {
        "0": "Initial state",
        "1": "Have been introduced",
        "3": "Felt like garbage",
        "9": "Did not feel like garbage"
    }],
    ["current_napstablook_song", "Which of Napstablook's songs is currently playing. Setting this value outside of the area might cause problems (but most of these do that).", [
        "Initial state",
        "Spooktune",
        "Spookwave",
        "Ghouliday"
    ]],
    ["aaron_woshua_event", "Whether you encountered Aaron and Woshua while one of Napstablook's songs was playing. Necessary for Aaron's yellow credit.", basicBool],
    ["conversation_emblem", "How much you've talked with Gerson about the Delta Rune.", [
        "Initial state",
        "'That emblem'",
        "'Emblem's meaning'",
        "'The prophecy'"
    ]],
    ["creepy_friend_seen", "Whether the NPC in room_water_prebird saw your creepy friend. The room is unused.", basicBool],
    ["saved_mkid", "What you did to Monster Kid.", [
        "Initial state/ran away",
        "Stayed, did nothing",
        "Saved them"
    ]],
    ["undyne_times_fought", "Stores how many times you have fought/run from Undyne. (Also increased at the end of each phase.) Alters her dialogue."],
    ["got_ribbon", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the ground.", basicBool],
    ["unused"],
    ["got_toyknife", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the ground.", basicBool],
    ["got_bscotch_pie", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the ground.", [
        "Initial state",
        "Floor pie",
        "Item acquired"
    ]],
    ["got_quiche", "Self-explanatory. Does not directly affect your inventory, only the item's presence under the bench.", basicBool],
    ["got_tutu", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the ground.", basicBool],
    ["got_ballet_shoes", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the ground.", basicBool],
    ["got_artifact", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the pedestal.", [
        "Initial state",
        "Artifact gone",
        "Dog in inventory"
    ]],
    ["got_spacefood", "Status of the Astronaut Food cooler.", [
        "Initial state",
        "Interacted with",
        "One taken",
        "Both taken"
    ]],
    ["got_instant_noodles", "Self-explanatory. Does not directly affect your inventory, only the item's presence in the fridge.", basicBool],
    ["got_frying_pan", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the ground.", basicBool],
    ["got_apron", "Self-explanatory. Does not directly affect your inventory, only the item's presence on the ground.", basicBool],
    ["got_glamburger_trashcan", "Whether you took the Glamburger from a trashcan in the CORE.", basicBool],
    ["got_gold_trashcan", "Whether you took the G from a trashcan in the CORE.", basicBool],
    ["got_dagger", "Self-explanatory. Does not directly affect your inventory, only the item's presence in the box.", basicBool],
    ["got_locket", "Self-explanatory. Does not directly affect your inventory, only the item's presence in the box.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["spared_froggit", "Whether you Complimented Froggit. Used for its yellow credit.", basicBool],
    ["spared_whimsun", "Whether you Consoled Whimsun. Used for its yellow credit.", basicBool],
    ["spared_moldsmal", "Whether you Flirted with/Imitated Moldsmal. Used for its yellow credit.", basicBool],
    ["spared_loox", "Whether you Didn't Pick On Loox. Used for his yellow credit.", basicBool],
    ["spared_vegetoid", "Whether you Spared Vegetoid. Used for its yellow credit.", basicBool],
    ["spared_migosp", "Whether you Spared or Talked to Migosp. Used for its yellow credit.", basicBool],
    ["spared_snowdrake", "Whether you Laughed at Snowdrake's joke. Used for his yellow credit.", basicBool],
    ["spared_icecap", "Whether you Complimented Ice (after Stealing its hat). Used for its yellow credit.", basicBool],
    ["spared_gyftrot", "Whether you removed three items from Gyftrot. Used for its yellow credit.", basicBool],
    ["spared_doggo", "Whether you Petted Doggo. Used for his yellow credit.", basicBool],
    ["spared_nuzzle_champs", "Whether you successfully petted both Dogi. Used for their yellow credit.", basicBool],
    ["spared_lesserdog", "Whether you Petted Lesser Dog four times. Used for its yellow credit.", basicBool],
    ["spared_greatdog", "Whether Greater Dog's pet capacity reached 100%. Used for its yellow credit.", basicBool],
    ["spared_aaron", "Whether Aaron flexed himself out of the room. Unaccessed (see flag 95).", basicBool],
    ["spared_moldsmalx", "Whether you Unhugged Moldbygg. Used for its yellow credit.", basicBool],
    ["spared_woshua", "Whether you Spared Woshua without damaging him. Used for his yellow credit.", basicBool],
    ["spared_temmie", "Whether you Talked to or gave Temmie the Temmie Flakes. Used for her yellow credit.", basicBool],
    ["spared_maddummy", "Whether you Talked to Mad Dummy. Used for their yellow credit.", basicBool],
    ["spared_vulkin", "Whether you Spared Vulkin without damaging it. Used for its yellow credit.", basicBool],
    ["spared_tsunderplane", "Whether you Spared Tsunderplane without damaging it. Used for its yellow credit.", basicBool],
    ["spared_pyrope", "Whether you Spared Pyrope without damaging it. Used for its yellow credit.", basicBool],
    ["spared_finalfroggit", "Whether you Spared Final Froggit without damaging it. Used for its yellow credit.", basicBool],
    ["spared_whimsalot", "Whether you Spared Whimsalot without damaging it. Used for its yellow credit.", basicBool],
    ["spared_astigmatism", "Whether you Spared Astigmatism without damaging it. Used for its yellow credit.", basicBool],
    ["spared_madjick", "Whether you Spared Madjick without damaging it. Used for its yellow credit.", basicBool],
    ["spared_finalknight", "Whether you Spared Knight Knight without damaging her. Used for her yellow credit.", basicBool],
    ["spared_endogeny", "Whether you satisfied Endogeny. Used for the Amalgamates' yellow credit.", basicBool],
    ["status_mewmew", "Tracks the status of Mad Mew Mew. Switch-only.", [
        "Initial state",
        "Door opened",
        "Mew Mew spared",
        "Mew Mew killed"
    ]],
    ["image_mewmew", "Which overworld sprite Mad Mew Mew uses. Switch-only. (Options are approximate color scheme.)", [
        "Pink",
        "White",
        "Green"
    ]],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["talk_toriel_pacifist", "The number of times you have talked to Toriel in the True Pacifist ending."],
    ["talk_sans_pacifist", "The number of times you have talked to Sans in the True Pacifist ending."],
    ["talk_undyne_pacifist", "The number of times you have talked to Undyne in the True Pacifist ending."],
    ["unlock_napsta_pacifist", "Whether Undyne mentioned Napstablook yet in the True Pacifist ending. Alters Blooky's dialogue.", basicBool],
    ["talk_papyrus_pacifist", "The number of times you have talked to Papyrus in the True Pacifist ending."],
    ["talk_alphys_pacifist", "The number of times you have talked to Alphys in the True Pacifist ending."],
    ["talk_asgore_pacifist", "The number of times you have talked to Asgore in the True Pacifist ending."],
    ["talk_mettaton_pacifist", "The number of times you have talked to Mettaton in the True Pacifist ending."],
    ["talk_blooky_pacifist", "The number of times you have talked to Napstablook in the True Pacifist ending."],
    ["kills_area_pointer", "Assigned when moving between areas. Points at the area-specific kill counter.", {
        "0": "No area counter",
        "202": "Ruins",
        "203": "Snowdin",
        "204": "Waterfall",
        "205": "Hotland/CORE"
    }],
    ["kills", "Volatile kill counter, used to increment global.kills after a battle. Otherwise, global.kills is preferred and this is mostly redundant."],
    ["kills_ruins", "Your kill count in the Ruins. Can reach 22 or so, but you stop getting random encounters after 20."],
    ["kills_tundra", "Your kill count in Snowdin Forest. Can reach 18 or so, but you stop getting random encounters after 16."],
    ["kills_water", "Your kill count in Waterfall. Can reach 20 or so, but you stop getting random encounters after 18."],
    ["kills_hotland", "Your kill count in Hotland/CORE. Can reach 47 or so, but you stop getting random encounters after 40."],
    ["hide_hotland_npcs", "Debug variable. Prevents Hotland/CORE NPCs from appearing, even in the epilogue.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["genocide_ruins", "Whether you have completed the kill count for the Ruins. Alters the music in the area.", basicBool],
    ["genocide_tundra", "Whether you have completed the kill count for Snowdin Forest. Alters the music in the area (even if Genocide was previously aborted).", basicBool],
    ["genocide_water", "Whether you have completed the kill count for Waterfall. Alters the music in the area (even if Genocide was previously aborted).", basicBool],
    ["genocide_hotland", "Whether you have completed the kill count for Hotland (while in Hotland). Alters the music in the area (even if Genocide was previously aborted).", basicBool],
    ["genocide_core", "Whether you have completed the kill count for the CORE (while in the CORE). Unaccessed.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["nicecream_business2", "Whether you interacted with Nice Cream Guy in Hotland.", basicBool],
    ["killed_undyne_ex", "Whether you killed Undyne the Undying, a key point of the Genocide Route.", basicBool],
    ["killed_glad_dummy", "Whether you killed Glad Dummy.", basicBool],
    ["killed_snowman", "The number of times you have interacted with the Snowman on the Genocide Route. Correlates with the number of pieces taken.", "options"],
    ["interacted_crosswords", "Whether you interacted with the crossword puzzle. Alters Sans and Papyrus's dialogue in the scene.", basicBool],
    ["robbed_snowdin", "Whether you took the 758G from Snowdin Shop on Genocide.", basicBool],
    ["robbed_core", "Whether you took the 5G from the alley shop on Genocide.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["used_recovery_item", "Whether you used any consumable items. Alters Sans's Neutral ending dialogue.", basicBool],
    ["interacted_fakedog", "Whether you interacted with the dog-shaped Dog Residue in the Dog Room.", basicBool],
    ["delivered_seatea", "Whether you put a Sea Tea under the correct door at MTT Resort.", basicBool],
    ["delivered_cinnabun", "Whether you put a Cinnamon Bun under the correct door at MTT Resort.", basicBool],
    ["delivered_hotdog", "Whether you put a Hot Dog under the correct door at MTT Resort.", basicBool],
    ["tem_sell_parameter", "The number of items you need to sell (0-9) before Temmie takes particular interest in one. Decrements with all sales except Tem Flakes."],
    ["tem_flakes_sold", "If false, the first Tem Flakes you sell will be at a premium. After that, the flag is set to true.", basicBool],
    ["status_hotel", "Tracks progress of the MTT Resort hotel. A value of 2 prevents the receptionist from repeating herself.", [
        "Initial state",
        "Stayed once",
        "Interacted again"
    ]],
    ["unused"],
    ["allergy_tem_talked", "Whether Tem has burst into hoivs.", basicBool],
    ["glowshrooms_on", "Whether you have visited Tem Village or completed the glow shroom puzzle. Causes the puzzle to remain lit.", basicBool],
    ["fighting_sans", "Whether you are currently fighting Sans. Used to render KR.", basicBool],
    ["geeettttttt_dunked_on", "Self-explanatory.", basicBool],
    ["unused"],
    ["unused"],
    ["tundra_stick_broken", "Tracks progress through Sans's introduction cutscene. See also flag 47.", [
        "Initial state",
        "Stick broken",
        "Sans seen between trees"
    ]],
    ["temmie_college_paid", "Self-explanatory. Unlocks a dialogue option about Temmie Armor.", basicBool],
    ["fun_call_occurred", "Whether you've received a fun-value phone call. Prevents the call from repeating.", basicBool],
    ["completed_tile_puzzle", "Whether you actually completed Mettaton's tile puzzle. Alters Papyrus's phone call in the room.", basicBool],
    ["interacted_clamgirl", "Whether you spoke with Clam Girl before the pacifist ending. Summons the 'don't forget' photograph in Sans's basement.", basicBool],
    ["conversation_elderpuzzles", "Your progress with the Elder Puzzler.", [
        "Initial state",
        "Received suggestion",
        "'Bah!'"
    ]],
    ["status_sosorry", "Self-explanatory.", [
        "Initial state",
        "Killed",
        "Spared"
    ]],
    ["encountered_glyde", "Self-explanatory. Unaccessed (you can fight him again).", basicBool],
    ["dated_papyrus2", "A mostly redundant flag (see 88) for completing Papyrus's date.", basicBool],
    ["undyne_spears_anger1", "Whether Undyne reached her maximum spear-throwing speed (around 100 volleys). Affects Monster Kid's following dialogue.", basicBool],
    ["undyne_spears_anger2", "Whether Undyne reached her maximum spear-stabbing speed around 82 volleys. Unaccessed.", basicBool],
    ["conversation_toriel_sms", "The number of text messages you have received from Toriel."],
    ["sms_parameters", "The number of text messages you are 'allowed' to receive from Toriel. Increments when moving between rooms until all messages are received."],
    ["failed_defusing", "Whether you ran out of defusing time while still in battle. Slightly alters dialogue.", basicBool],
    ["stepped_green_tile", "Whether you stepped on a green tile. Alters Mettaton's reason for fighting you.", basicBool],
    ["papyrus_special_attack", "Whether you fought Papyrus on Genocide. Alters dialogue if he is spared.", "options"],
    ["geno_electric_puzzle", "Whether you reached the Invisible Electricity Maze on Genocide. Affects Papyrus's phone call in the room if he is spared.", basicBool],
    ["shrine_donation_amount", "The amount of G dognated to the Dog Shrine."],
    ["shrine_donation_goal", "The amount of G for the next dognation level (e.g. '5 out of 70' not '65 more')."],
    ["dog_shrine_level", "The current dognation level of the Dog Shrine (0-15)."],
    ["shrine_text_progression", "Prevents the Dog Shrine from repeating its description after certain upgrades. (0-6)"],
    ["donation_box_usable", "Whether you have interacted with the dognation box in the Garbage Dump. Allows you to start dognating to it.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["dimensional_box_A_1", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_2", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_3", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_4", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_5", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_6", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_7", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_8", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_9", "The item in a given slot of a given box.", items],
    ["dimensional_box_A_10", "The item in a given slot of a given box.", items],
    ["box_A_interacted", "Whether you have interacted with Dimensional Box A. Unaccessed.", {
        "0": "Initial state",
        "999": "Interacted" // probably not intended for this but that's the only thing it does
    }],
    ["unused"],
    ["dimensional_box_B_1", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_2", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_3", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_4", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_5", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_6", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_7", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_8", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_9", "The item in a given slot of a given box.", items],
    ["dimensional_box_B_10", "The item in a given slot of a given box.", items],
    ["box_B_interacted", "Whether you have interacted with Dimensional Box B. Unaccessed.", {
        "0": "Initial state",
        "999": "Interacted"
    }],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["status_undyne", "Self-explanatory.", [
        "Initial state",
        "Killed",
        "Sick"
    ]],
    ["undyne_hp_left", "How much HP Undyne has. Used to persist it even when you flee."],
    ["fought_undyne", "Self-explanatory. Alters her dialogue upon returning to finish the fight.", basicBool],
    ["poured_water_ground", "The amount of water poured on the ground (0-21). Affects the puddle size and Clam Guy's dialogue."],
    ["conversation_papyrus_calls", "Your loose progress through Waterfall as monitored by Papyrus's phone calls.", [
        "Initial state",
        "Received second clothes call",
        "Received Undyne hangout suggestion"
    ]],
    ["choice_maddummy", "Your interaction with the Mad Dummy before fighting it.", [
        "Initial state",
        "Punched",
        "Spared"
    ]],
    ["completed_piano_puzzle", "Self-explanatory.", basicBool],
    ["progress_water_battles", "How many Waterfall encounters you've had before Onionsan. Guarantees you encounter a variety of enemies.", [
        "Initial state",
        "Fought Aaron",
        "Fought Woshua",
        "Fought Moldsmals",
        "[4] And so on..."
    ]],
    ["progress_water2_battles", "How many Waterfall encounters you've had after Shyren. Guarantees you encounter a variety of enemies.", [
        "Initial state",
        "Fought Temmie",
        "Fought Moldsmal + Moldbygg",
        "Fought Woshua + Aaron",
        "Fought Moldbygg + Woshua",
        "[5] And so on..."
    ]],
    ["unused"],
    ["rain_unmuted", "Whether the rain in Waterfall is making sound. IGNORED IN LOADING.", basicBool],
    ["rain_track1_volume", "The volume of one of the rain tracks (0-0.5). IGNORED IN LOADING."],
    ["rain_track2_volume", "The volume of the other rain track (0-0.5). IGNORED IN LOADING."],
    ["rain_track1", "The sound index of rain track 1. IGNORED IN LOADING.", {
        "0": "Uninitialized",
        "277": "rain.ogg (v1.08)"
    }],
    ["rain_track2", "The sound index of rain track 2. IGNORED IN LOADING.", {
        "0": "Uninitialized",
        "277": "rain_deep.ogg (v1.08)"
    }],
    ["unused"],
    ["have_water", "Whether you have a cup of water.", basicBool],
    ["disable_alphys_calls", "Self-explanatory. Only set on Genocide.", basicBool],
    ["disable_alphys_statuses", "Self-explanatory. Only set on Genocide.", basicBool],
    ["progress_alphys_statuses", "Progress with Alphys's statuses. Prevents them from repeating, even if you leave the room.", {
        "0": "Initial state",
        "2": "First status (post-lab)",
        "3": "Second status",
        "4": "Third status",
        "5": "Fourth status (conveyors)",
        "6": "Fifth status (vents)",
        "7": "Sixth status",
        "8": "Seventh status (lasers)",
        "9": "Eighth status",
        "10": "Ninth status (shooter hub)",
        "11": "Tenth status",
        "12": "Eleventh status (right shooter)",
        "13": "Twelfth status (vent chain)",
        "16": "Thirteenth status (branch to apron)",
        "17": "Papyrus status",
        "18": "Fifteenth status",
        "19": "Papyrus status 2",
        "20": "Seventeenth status (many vents)",
        "21": "Eighteenth status (Bad Opinion Zone)",
        "22": "Nineteenth status",
        "23": "Twentieth status",
        "24": "21st status (Royal Guards)",
        "25": "22nd status",
        "26": "Anime phonecall",
        "99": "Genocide"
    }],
    ["quick_battle", "An ID for the last quick battle you were in.", [
        "Initial state",
        "Undyne spears",
        "Hotland lasers",
        "CORE lasers"
    ]],
    ["laser1_off", "Whether the first lasers are, indeed, off.", basicBool],
    ["lasers_off", "Whether Alphys disabled the lasers for you because you got hurt. Alters dialogue and disables some later lasers.", basicBool],
    ["laser2_off", "Whether Alphys disabled the impassable laser.", basicBool],
    ["completed_shoot_puzzle1", "Whether you completed the left shooting puzzle.", basicBool],
    ["completed_shoot_puzzle2", "Whether you completed the right shooting puzzle.", basicBool],
    ["conveyor_puzzle_variable", "Persists the protagonist's x coordinate in the unused conveyor puzzle of room_fire10_old."],
    ["failed_jetpack_segment", "Whether you did, in fact, fail the jetpack segment.", basicBool],
    ["hot_dogs_money_spent", "The amount of money spent on hot dogs. Unaccessed."],
    ["conversation_hotdogs", "The number of hot animals bought."],
    ["headdogs", "The number of hot dogs on your head (0-30)."],
    ["reached_headdogs_limit", "Whether Sans has explained that thirty is the limit. Prevents him from repeating himself.", basicBool],
    ["muffet_bribe_price", "Muffet's current price to be bribed. Various, but trends upward."],
    ["muffet_bribe_money_spent", "Self-explanatory."],
    ["unused"],
    ["status_yellow_button", "Status of your phone's yellow button.", [
        "Initial state",
        "Available",
        "Pressed"
    ]],
    ["bridgeseed_puzzle1_solved", "Whether the first Bridge Seed puzzle is complete.", basicBool],
    ["won_ball_game", "Whether you earned the red flag. Alters reward amount and text.", basicBool],
    ["falling", "Whether you are currently falling from a Ruins puzzle. Keeps code from duplicating.", basicBool],
    ["dated_undyne", "Your progress in dating Undyne.", {
        "0": "Initial state",
        "3": "Left house",
        "4": "Undyne left",
        "5": "Date complete"
    }],
    ["undyne_expression", "Causes some changes to Undyne's faces.", [
        "Default",
        "Sweating",
        "Tomato-covered"
    ]],
    ["choice_meal_grillby", "The meal you got with Sans.", [
        "Initial state",
        "Fries",
        "Burger"
    ]],
    ["unused"],
    ["wizard_orb_special", "Used as a sound index for a Madjick Easter Egg. Unset.", {
        "0": "Initial state",
        "296": "mus_star.ogg (v1.08)"
    }],
    ["unused"],
    ["bombs_defused", "Self-explanatory. 0-6."],
    ["muffet_progress", "Progress through the pre-Muffet fight scene.", [
        "Initial state",
        "First textbox",
        "Second textbox",
        "Third textbox",
        "Fourth textbox",
        "Fifth textbox",
        "Muffet defeated"
    ]],
    ["killed_muffet", "Self-explanatory.", basicBool],
    ["current_elevator_floor", "Manages the elevator choicer and your destination.", [
        "L1",
        "R1",
        "R2",
        "L2",
        "L3",
        "R3"
    ]],
    ["completed_shoot_puzzle3", "Whether you completed the bottom shooting puzzle.", basicBool],
    ["completed_shoot_puzzle4", "Whether you completed the top shooting puzzle.", basicBool],
    ["asked_papyrus_rg", "Whether Undyne explained the brainwashing in Mew Mew Kissie Cutie. Alters the Royal Guard encounter.", basicBool],
    ["killed_rg", "Self-explanatory.", basicBool],
    ["spider_sale_big_spendings", "Whether you've bought from the expensive bake sale. Unaccessed.", basicBool],
    ["laser3_off", "Whether you managed to hit all three switches despite the call (glitches required). Unaccessed.", basicBool],
    ["conversation_wares", "How much you've talked with Bratty and Catty about their wares.", [
        "Initial state",
        "'About your wares'",
        "'Origin of wares'",
        "'Origin of garbage'"
    ]],
    ["conversation_mettaton", "How much you've talked with Bratty and Catty about Mettaton.", [
        "Initial state",
        "'About Mettaton'",
        "'Origin of Mettaton'"
    ]],
    ["conversation_alphys", "How much you've talked with Bratty and Catty about Alphys.", [
        "Initial state",
        "'About Alphys'",
        "'Royal Scientist'",
        "'About ASGORE'"
    ]],
    ["progress_hotland_battles", "How many Hotland (not CORE) encounters you've had. Guarantees you encounter a variety of enemies.", [
        "Initial state",
        "Fought Vulkin",
        "Fought Tsunderplane",
        "Fought Pyrope",
        "Fought Tsunderplane + Vulkin",
        "Fought Pyrope x2",
        "[6] And so on..."
    ]],
    ["got_napstablook_friend_req", "Whether you got Napstablook's self-rejecting friend request.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["dated_sans2", "Progress through dating Sans at MTT Resort.", [
        "Initial state",
        "In date",
        "Date complete"
    ]],
    ["got_alphys_advice1", "Whether you have attempted to take the elevator through the CORE.", basicBool],
    ["got_alphys_advice2", "Whether you have attempted to take the right path through the CORE.", basicBool],
    ["got_alphys_advice3", "Whether Alphys has told you not to head right, or if she's bailed.", basicBool],
    ["got_alphys_advice4", "Whether you have fought the scripted Knight Knight battle.", basicBool],
    ["core_shooter_complete", "Whether you have completed the final shooter puzzle. Unlocks the End.", basicBool],
    ["warriors_path_complete", "Whether you have completed the Warrior's Path. Unlocks the End.", basicBool],
    ["core_laser_timeout", "Whether you have waited the full minute. Unlocks the End.", basicBool],
    ["warriors_path_progression", "Your progression through the Warrior's Path.", [
        "Initial state",
        "Whimsalot + Final Froggit defeated",
        "Knight Knight + Madjick defeated",
        "'Nightmare' team defeated"
    ]],
    ["unused"],
    ["progress_core_battles", "Ensures a variety of encounters... for the unused obj_lazyencounterer_core."],
    ["turn_mettaton", "Status of turning around Mettaton.", [
        "Initial state",
        "Available",
        "Pressed"
    ]],
    ["killed_mettaton", "Whether you have killed Mettaton.", basicBool],
    ["progress_core_battles2", "How many CORE (not Hotland) encounters you've had. Guarantees you encounter a variety of enemies.", [
        "Initial state",
        "Fought Astigmatism",
        "Fought Whimsalot + Final Froggit",
        "Fought Whimsalot + Astigmatism",
        "Fought Final Froggit + Astigmatism",
        "Fought Knight Knight + Madjick",
        "[6] And so on..."
    ]],
    ["unused"],
    ["unused"],
    ["unused"],
    ["alphys_expression", "Controls which set of facial expressions Alphys is currently using.", [
        "Default",
        "Panicked (after Mettaton)",
        "Depressed (after Mettaton)",
        "Repentant (lab end)",
        "Resolute (Alphys ending)"
    ]],
    ["current_final_floor", "Which direction you are currently going or last took in the final elevator.", [
        "CORE",
        "New Home"
    ]],
    ["rode_long_elevator", "Whether you already took the long elevator. Significantly shortens the ride.", basicBool],
    ["unlocked_mettaton_house", "Whether you've unlocked the pink house.", basicBool],
    ["choice_flamey_challenge", "Your response to Heats Flamesman.", [
        "Initial state",
        "Remembered",
        "Forgot"
    ]],
    ["status_bpants", "Your progress toward talking with Burgerpants.", [
        "Initial state",
        "Made purchase",
        "Talked"
    ]],
    ["conversation_mtt", "How much you've talked with Burgerpants about Mettaton.", [
        "Initial state",
        "'Mettaton'",
        "'Why is Mettaton bad'",
        "'Why else is MTT bad'"
    ]],
    ["conversation_girls", "How much you've talked with Burgerpants/Bratty and Catty about each other.", {
        "0": "Initial state",
        "1": "Bpants: 'Romance Advice'",
        "2": "Bpants: 'Glamburger Story'",
        // bruh making me use a dictionary
        "4": "Girls: 'Burgerpants'",
        "5": "Girls: 'More Burgerpants'",
        "6": "Bpants: 'Bratty & Catty'",
        "7": "Girls: 'B.Pants Hangout?'",
        "8": "Girls: 'That Kind of Guy'",
        "9": "Bpants: 'Catty's Invitation'"
    }],
    ["unused"],
    ["unused"],
    ["water_taken_amount", "The amount of water taken from the Hotland cooler."],
    ["water_wasted_amount", "The amount of water poured out in front of Undyne. Unaccessed."],
    ["got_gun", "Whether you purchased the Empty Gun, a unique item.", basicBool],
    ["got_cowboy_hat", "Whether you purchased the Cowboy Hat, a unique item.", basicBool],
    ["got_mystery_key", "Whether you purchased the Mystery Key, a unique item.", basicBool],
    ["got_face_steak", "Whether you purchased the Face Steak, a unique item.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["progress_story", "Loosely, How much of Asriel's story you've heard.", [
        "Initial state",
        "'A long time ago'",
        "2-3 encounters (see 455-456)",
        "'Very ill' (basement)",
        "'One request'",
        "'The human died'",
        "'Incredible power'",
        "'Into the sunset'",
        "'Golden flowers'",
        "'The villagers saw ASRIEL'",
        "'Blow after blow'",
        "'ASRIEL smiled'",
        "'Across the garden'",
        "'Fell into despair'",
        "'End our suffering'",
        "'Not long now'",
        "'You should be smiling'",
        "'You're going to be free'"
    ]],
    ["unused"],
    ["have_castle_key1", "Whether you have the kitchen key.", basicBool],
    ["have_castle_key2", "Whether you have the bedrooms key.", basicBool],
    ["unlocked_latchkey", "Your progress in unlocking Asgore's basement.", {
        "0": "Initial state",
        "0.5": "Interacted with",
        "1": "Unlocked"
    }],
    ["early_story_parameter1", "How many story encounters you got (0-2) en route to the kitchen. Prevents a 'fourth' encounter."],
    ["early_story_parameter2", "How many story encounters you got (0-2) en route to the bedrooms. Prevents a 'fourth' encounter."],
    ["told_asgore_ready", "Whether you said you weren't ready. Slightly alters Asgore's dialogue on returning.", basicBool],
    ["experience_cosmic_garbage", "Whether you have felt like garbage with Napstablook. Alters their dialogue afterward.", basicBool],
    ["riverman_destination", "The destination you selected with River Person.", [
        "Initial state",
        "Snowdin",
        "Waterfall",
        "Hotland"
    ]],
    ["riverman_times_rode", "The amount of fast travel you have found use for in such a short game."],
    ["tem_boat_version", "Whether your last boat ride featured the dog face. (It alternates.)", basicBool],
    ["called_already", "The number of phone calls you have made in the current room. Only has effects beyond 2."],
    ["unused"],
    ["unused"],
    ["papyrus_and_undyne", "Whether Undyne can be called with Papyrus (after her date).", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["conversation_undyne_mad", "Whether Undyne and Papyrus have discussed meterology on the phone. Prevents her from repeating it, even if you re-enter the room.", basicBool],
    ["unused"],
    ["unused"],
    ["unused"],
    ["unused"],
    ["killed_flowey", "Self-explanatory.", basicBool],
    ["killed_asgore", "Self-explanatory.", basicBool],
    ["unused"],
    ["unused"],
    ["truelab_unsuppress_border", "Whether the True Lab border has been unlocked. Maintains the border when backtracking to the first two initially-borderless rooms.", basicBool],
    ["inside_truelab", "Whether you are inside the True Lab. Darkens obj_mainchara appropriately.", basicBool],
    ["truelab_red_key_status", "Status of the red key.", [
        "Initial state",
        "In sink",
        "Collected",
        "In slot"
    ]],
    ["truelab_blue_key_status", "Status of the blue key.", [
        "Initial state",
        "On ground",
        "Collected",
        "In slot"
    ]],
    ["truelab_green_key_status", "Status of the green key.", [
        "Initial state",
        "In tub",
        "Collected",
        "In slot"
    ]],
    ["truelab_yellow_key_status", "Status of the yellow key.", [
        "Initial state",
        "On bed",
        "Collected",
        "In slot"
    ]],
    ["truelab_complete", "Whether you have restored power. Activates the 'creepy' lab monitors.", basicBool],
    ["truelab_sink_interact_count", "The number of times you have turned on True Lab sinks. Used for Memoryhead spawning, after which it jumps to 10."],
    ["truelab_sink_key", "Which sink has the key in it.", [
        "None",
        "Left sink",
        "Middle sink",
        "Right sink"
    ]],
    ["truelab_spared_reaperbird", "Whether you have defeated Reaper Bird.", basicBool],
    ["truelab_spared_lemon", "Whether you have defeated Lemon Bread.", basicBool],
    ["truelab_spared_endogeny", "Whether you have defeated Endogeny.", basicBool],
    ["truelab_elevator_power", "Whether the power switch has been flipped (kind of redundant to 485).", basicBool],
    ["enable_alphys_date", "Whether you've defeated Mettaton, locking the door to the Lab until Alphys is dated (when it is reset to 0)", basicBool],
    ["true_pacifist_progression", "Tracks progress through True Pacifist.", {
        "0": "Initial state",
        "8": "Undyne waiting with letter",
        "9": "Letter acquired",
        "10": "Alphys date complete",
        "11": "Received Papyrus call",
        "12": "True Lab complete"
    }],
    ["status_undyne_letter", "Status of dropping Undyne's Letter.", {
        "0": "Initial state",
        "1": "Dropped",
        "3": "Received EX letter"
    }],
    ["popato_chisps_bought", "Amount of potato chisps you have bought. (0-8)"],
    ["conversation_onionsan", "Onionsan's status.", {
        "-1": "Rejected",
        "0": "Initial state",
        "1": "Onionsan appeared",
        "2": "'It's my Big Favorite'",
        "3": "'Like all my friends did'",
        "4": "'Undyne's gonna fix everything'",
        "5": "'See you around'",
        "6": "'I'm starting a band'",
        "7": "Met in epilogue"
    }],
    ["got_sans_room_key", "Progress with Sans's keys.", [
        "Initial state",
        "Got room key",
        "Entered room",
        "Got silver key"
    ]],
    ["unused"],
    ["seen_cast", "Whether the credits have activated, keeps them from re-activating even when the room changes.", basicBool],
    ["but_it_refused", "Cannot die.", basicBool],
    ["conversation_asriel_fight", "Progress in Asriel's second phase.", [
        "Initial state",
        "SAVE available",
        "All friends SAVED",
        "Begun SAVING Asriel"
    ]],
    ["refuse_count", "Number of times you died to Asriel."],
    ["dreamed_asriel_fight", "Whether you have Dreamed yet. Alters the Dream narration.", basicBool],
    ["asriel_turn_restore_point", "The turn that will be reloaded to when you refuse to die to Asriel."],
    ["saved_undyne", "Self-explanatory.", basicBool],
    ["saved_alphys", "Self-explanatory.", basicBool],
    ["saved_papyrus_sans", "Self-explanatory.", basicBool],
    ["saved_toriel_asgore", "Self-explanatory.", basicBool],
    ["decimal_hp_state", "Overrides the HP writer for the low decimals.", [
        "Initial state",
        "00.001",
        "00.0001",
        "00.000001",
        "00.0000000001"
    ]],
    ["plot_over", "Somewhat controls the waking-up scene after the Asriel fight.", [
        "Initial state",
        "Scene started",
        "Scene complete"
    ]],
    ["conversation_asriel2", "The amount you have talked to Asriel in the Ruins."],
    ["choice_left_toriel", "Your choice in the final scene.", [
        "I want to stay with you",
        "I have places to go"
    ]]
];
